// app/layout.tsx
import type { Metadata } from "next";
import { Rubik } from 'next/font/google';
import "@/style/globals.css";
import ClientLayout from "./clientLayout"; // Импортируйте новый компонент
import { AuthProvider } from "../utils/authContext";

const inter = Rubik({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className}`} style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', overflowX: 'hidden' }}>
                <AuthProvider>
                    <ClientLayout>{children}</ClientLayout>
                </AuthProvider>

            </body>
        </html>
    );
}
